### ISSUE TITLE
Support durationSeconds on AssumeRoleWithSAMLReques

### ISSUE THREAD

**Issue by pitbulk** [onelogin/onelogin-aws-cli-assume-role#11]
Currently the toolkit executes AssumeRoleWithSAMLRequest without set the [durationSeconds](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sts/src/main/java/com/amazonaws/services/securitytoken/model/AssumeRoleWithSAMLRequest.java#L104)

On the current aws-java-sdk-sts version used ([1.11.191](https://github.com/aws/aws-sdk-java/blob/1.11.191/aws-java-sdk-sts/src/main/java/com/amazonaws/services/securitytoken/model/AssumeRoleWithSAMLRequest.java) the value initialization was omitted because by default is set to
3600 (1h) that was the max, but in a newer version that changed and the setting can
have a value from 1 hour to 12 hours.

See [role's maximum session duration setting (AWS API)](http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use.html#id_roles_use_view-role-max-session)

**Comment by rfein-hearst** [comment]
👍  please

**Comment by tzahiba** [comment]
Please !

**Comment by marky-mark** [comment]
forking and ill send in a PR

**Comment by pitbulk** [comment]
I already implemented this and other features, but still testing the code.

**Comment by marky-mark** [comment]
ok ill wait, thanks

**Comment by jutley** [comment]
Any idea when we will get this feature? We're revamping our Kubernetes authentication strategy, and being able to support 12 hour tokens would be a huge help.
