### ISSUE TITLE
Publish github releases versions

### ISSUE THREAD

**Issue by codergolem** [onelogin/onelogin-aws-cli-assume-role#13]
Hi,

We scripted the process of downloading the jar artifact  and it would be very useful if we could check the latest released version using the github api.
At the moment under releases regular tags are shown so the api request for releases is empty e.g ```curl https://api.github.com/repos/onelogin/onelogin-aws-cli-assume-role/releases``` . 
This feature is already used for the python version of the cli ```curl https://api.github.com/repos/onelogin/onelogin-python-aws-assume-role/releases``` so I guess it would not imply much effort.

thx

**Comment by pitbulk** [comment]
Noted, I will also add release at github on the next release.
